### ISSUE TITLE
Incorrectly instantiated DateTimes

### ISSUE THREAD

**Issue by repli2dev** [nette/di#116]
I attempted to use DateTime as parameter value in my config:
```
parameters:
    date: 2016-09-01
php:
    date.timezone: Europe/Prague
```

The parameter `date` is instanciated (that's cool), however this is done in the PHP default time zone which is (for example) `UTC` whereas I explicitly specify that I want to use `Europe/Prague`.

From brief look inside the source codes I understand that the sections are processed separetly, however this behaviour is highly unexpected and I would consider it a pitfall as it the bugs caused are not easy to find.
