### ISSUE TITLE
Unable to overwrite service arguments

### ISSUE THREAD

**Issue by janedbal** [nette/di#128]
Following configuration will merge arguments instead of overwriting them and I could not find any way to remove old arguments (`$foo`) or solve it differently than defining the services without using `arguments`. Is there any way to do it? Or maybe overwriting arguments would be better than merging (when I change class), what do you think?

```yaml
# global.neon
services:
    a:
        class: Foo
        arguments:
            foo: value1
```
```yaml
# local.neon
services:
    a:
        class: Bar
        arguments:
            bar: value2
```
```php
class Foo {
	public function __construct($foo) {}
}
class Bar {
	public function __construct($bar) {}
}

$configurator = new \Nette\Configurator();
$configurator->setTempDirectory(__DIR__ . '/temp');
$configurator->addConfig(__DIR__ . '/global.neon');
$configurator->addConfig(__DIR__ . '/local.neon');
$container = $configurator->createContainer();

$container->getService('a'); // Unable to pass specified arguments to Bar::__construct()
```
