### ISSUE TITLE
Multiple services exception should be before invalid service exception

### ISSUE THREAD

**Issue by janbarasek** [nette/di#217]
Hello,

I think in case of very long neon file:

```yaml
parameters:
	cart:
		expiration: 14 days

services:
	# some services ...
	- Shop\CartStorage
	# some services ...

	# cart
	- Shop\CartManager
	- Shop\CartStorage(%cart.expiration%)
```

I can easily overlook a class definition error.

Because in this case exception will be:

`Service of type Shop\CartStorage: Parameter $expiration in __construct() has no class type hint or default value, so its value must be specified.`

Service class:

```php
class CartStorage {
	public function __construct(string $expiration, ...
```

But this is unexpected behavior.

I think it should first get the error that the service has multiple different definitions.

Now the developer needs to fix all dependencies first to find out that he was doing it unnecessarily, because the right definition already exists, he just didn't notice.

Thanks.
