### ISSUE TITLE
There is no way to write a password starting with @ (at) in NEON

### ISSUE THREAD

**Issue by janbarasek** [nette/di#248]
Version: v3.0.5

### Bug Description
I've been trying to look for different syntaxes, and I don't think there's any way to write a neon password starting with an at sign that is passed as a method argument.

### Steps To Reproduce
For example:

```yaml
parameters:
   myService:
      login: admin
      password: "@test"

services:
   - App\MyService(%myService.login%, %myService.password%)
```

The password is stored as a string parameter. Nevertheless, it will be used as a reference to the service.

It throws an exception:

> Nette\DI\ServiceCreationException
>
> Service `24` (type of `App\MyService`): Reference to missing service `'test'`.

### Expected Behavior & Possible Solution

The password stored in the string should be used as a string. Or there should be an alternate syntax for writing a string as a parameter to be used exactly in its wording.

Thank you!
