### ISSUE TITLE
Parameter removed if static method referenced [BC break]

### ISSUE THREAD

**Issue by repli2dev** [nette/di#312]
Version: 3.1.8 (3.1.3 not affected)

### Bug Description
After upgrading from 3.1.3 to 3.1.8 we got failing test due to missing parameters.

We have config like:
```
parameters:
  sms:
    - type: example
      key: example_key
    - type: example2
      key: example2_key
      handler: ExistingClass::staticMethodThatReturnsClosure()
```

In that situation after DI preprocessing the whole `sms` is missing from `$container->getParameters()` in 3.1.8 but was present in 3.1.3 (with `null` `handler`).

### Steps To Reproduce

Config above with 3.1.8 and up. Due to complex setup I was not able to minimise it further yet.

### Expected Behavior
The `sms` subtree does not goes missing entirely when there is a such code reference.

### Possible Solution
Access the config through another service with pasting the `%sms%` ... in that situation the handler is created correctly.
