### ISSUE TITLE
Overriding service definition with factory always requires return annotation

### ISSUE THREAD

**Issue by janedbal** [nette/di#58]
After migrating to 2.3, following behaviour changed (and I don't know if it is intentional, so I'm reporting it):

```yaml
# config.neon:
services:
    someService:
        class: Some\Class
       
# config.local.neon:
services:
    someService:
        factory: SomeFactory::create # doesn't have @return phpdoc
```       
       
Newly in 2.3 it raises ```User Notice: Type of service 'someService' is unknown.``` because it requires the ```@return``` phpdoc annotation in the factory. This worked without it in 2.2.

**Comment by dg** [comment]
You can check if this PR https://github.com/nette/di/pull/39 helps?

**Comment by janedbal** [comment]
Actually, it doesn't.

**Comment by dg** [comment]
Can you test it on sandbox? It works to me.

**Comment by janedbal** [comment]
Doesn't work even on sandbox. I've used following composer dependencies and replaced DI/Compiler with [this content](https://raw.githubusercontent.com/dg/nette-di/pull-overide/src/DI/Compiler.php). The ```create``` method in factory is static.

```json
{
	"require": {
		"nette/nette": "~2.3.0"
	},
	"minimum-stability": "dev",
	"prefer-stable": true
}
```

**Comment by dg** [comment]
Can you upload sandbox anywhere?

**Comment by janedbal** [comment]
[Here it is](http://uloz.to/x8GnfKDi/sandbox-zip)

**Comment by dg** [comment]
And this works with 2.2? I do not believe. You simply cannot merge value with array ie.

```yaml
# config.neon:
services:
    someService:  #array
        class: Some\Class
       
# config.local.neon:
services:
    someService: SomeFactory::create  #value
```
